export const effects = {
    0: "Stimulant",
    1: "Depressant",
    2: "Hallucinogenic",
    3: "Empathogenic/Entactogenic",
    4: "Dissociative",
    5: "Psychedelic",
    6: "Sedative",
    7: "Anxiolytic",
    8: "Analgesic/Pain Relief",
    9: "Antidepressant",
    10: "Nootropic/Cognitive Enhancement",
    11: "Anti-inflammatory",
    12: "Anti-anxiety",
    13: "Anti-psychotic",
    14: "Muscle Relaxant",
    15: "Euphoric",
    16: "Aphrodisiac",
    17: "Neuroprotective",
    18: "Sleep Aid/Hypnotic",
    19: "Mood Stabilizer",
    20: "Performance Enhancement",
    21: "Anti-convulsant",
    22: "Anti-addictive",
    23: "Immune Modulating",
    24: "Antiviral",
    25: "Antibacterial",
    26: "Anti-cancer",
    27: "Hormonal Regulation",
    28: "Bronchodilator",
    29: "Anti-diabetic",
    30: "Anti-hypertensive",
    31: "Vasodilator",
    32: "Psychoactive",
    33: "Anti-nausea",
    34: "Diuretic",
    35: "Anti-fungal",
    36: "Cannabinoid-like",
    37: "Serotonergic",
    38: "Dopaminergic",
    39: "Opioid-like",
    40: "Adrenergic"
}